[menu]

  [[menu.main]]
  identifier = "shop/"
  url = "shop/"
  name = "Shop"
  weight = 1.0

  [[menu.main]]
  url = "product-category/body-products/"
  name = "Body Products"
  parent = "shop/"
  weight = 10.0

  [[menu.main]]
  url = "product-category/dog-food-from-feed-me-free-range/"
  name = "Dog Food"
  parent = "shop/"
  weight = 11.0

  [[menu.main]]
  identifier = "product-category/drinks/"
  url = "product-category/drinks/"
  name = "Drinks"
  parent = "shop/"
  weight = 12.0

  [[menu.main]]
  url = "product-category/coffee/"
  name = "Coffee and Tea"
  parent = "product-category/drinks/"
  weight = 100.0

  [[menu.main]]
  identifier = "product-category/kefir/"
  url = "product-category/kefir/"
  name = "Kefir"
  parent = "product-category/drinks/"
  weight = 101.0

  [[menu.main]]
  url = "product-category/kefir/coconut-kefir/"
  name = "Coconut Kefir"
  parent = "product-category/kefir/"
  weight = 1000.0

  [[menu.main]]
  url = "product-category/kefir/milk-kefir/"
  name = "Milk Kefir"
  parent = "product-category/kefir/"
  weight = 1001.0

  [[menu.main]]
  url = "product-category/kefir/water-kefir/"
  name = "Water Kefir"
  parent = "product-category/kefir/"
  weight = 1002.0

  [[menu.main]]
  url = "product-category/kombucha/"
  name = "Kombucha"
  parent = "product-category/drinks/"
  weight = 102.0

  [[menu.main]]
  url = "product-category/non-dairy-milk/"
  name = "Non dairy milk"
  parent = "product-category/drinks/"
  weight = 103.0

  [[menu.main]]
  url = "product-category/water/"
  name = "Water"
  parent = "product-category/drinks/"
  weight = 104.0

  [[menu.main]]
  identifier = "product-category/food/"
  url = "product-category/food/"
  name = "Food"
  parent = "shop/"
  weight = 13.0

  [[menu.main]]
  url = "product-category/butter/"
  name = "Butter"
  parent = "product-category/food/"
  weight = 100.0

  [[menu.main]]
  identifier = "product-category/chocolate-2/"
  url = "product-category/chocolate-2/"
  name = "Chocolate and other treats"
  parent = "product-category/food/"
  weight = 101.0

  [[menu.main]]
  url = "product-category/chocolate-treats-gluten/"
  name = "Chocolate Treats"
  parent = "product-category/chocolate-2/"
  weight = 1000.0

  [[menu.main]]
  url = "product-category/food/chocolate-2/other-treats/"
  name = "Other Treats"
  parent = "product-category/chocolate-2/"
  weight = 1001.0

  [[menu.main]]
  url = "product-category/corn-chips-and-tortillas-from-santa-annas/"
  name = "Corn Chips and Tortillas"
  parent = "product-category/food/"
  weight = 102.0

  [[menu.main]]
  url = "product-category/dairy/"
  name = "Dairy"
  parent = "product-category/food/"
  weight = 103.0

  [[menu.main]]
  url = "product-category/eggs-from-feed-me-free-range/"
  name = "Eggs"
  parent = "product-category/food/"
  weight = 104.0

  [[menu.main]]
  url = "product-category/falafel-ready-mix/"
  name = "Falafel Ready Mix"
  parent = "product-category/food/"
  weight = 105.0

  [[menu.main]]
  identifier = "product-category/fish/"
  url = "product-category/fish/"
  name = "Fish"
  parent = "product-category/food/"
  weight = 106.0

  [[menu.main]]
  url = "product-category/fish/fresh-and-smoked-trout/"
  name = "Two Dam Sustainable"
  parent = "product-category/fish/"
  weight = 1000.0

  [[menu.main]]
  url = "product-category/fish/green-fish/"
  name = "Green Fish"
  parent = "product-category/fish/"
  weight = 1001.0

  [[menu.main]]
  identifier = "product-category/flour-grain-free-from-crede/"
  url = "product-category/flour-grain-free-from-crede/"
  name = "Flour"
  parent = "product-category/food/"
  weight = 107.0

  [[menu.main]]
  url = "product-category/flour-grain-free-from-crede/grain-flours/"
  name = "Grain Flours"
  parent = "product-category/flour-grain-free-from-crede/"
  weight = 1000.0

  [[menu.main]]
  url = "product-category/flour-grain-free-from-crede/grain-free-flours/"
  name = "Grain Free Flours"
  parent = "product-category/flour-grain-free-from-crede/"
  weight = 1001.0

  [[menu.main]]
  url = "product-category/flour-grain-free-from-crede/oraganic-sprouted-flour/"
  name = "Organic Sprouted Flour"
  parent = "product-category/flour-grain-free-from-crede/"
  weight = 1002.0

  [[menu.main]]
  identifier = "product-category/food-and-nutrition-oils/"
  url = "product-category/food-and-nutrition-oils/"
  name = "Oils"
  parent = "product-category/food/"
  weight = 108.0

  [[menu.main]]
  url = "product-category/oils-from-crede/"
  name = "Food Oils"
  parent = "product-category/food-and-nutrition-oils/"
  weight = 1000.0

  [[menu.main]]
  url = "product-category/nutrition-oils-from-crede/"
  name = "Nutrition Oil"
  parent = "product-category/food-and-nutrition-oils/"
  weight = 1001.0

  [[menu.main]]
  url = "product-category/grains-and-pulses/"
  name = "Grains and Pulses"
  parent = "product-category/food/"
  weight = 109.0

  [[menu.main]]
  url = "product-category/handmade-ready-meals/"
  name = "Handmade ready meals"
  parent = "product-category/food/"
  weight = 110.0

  [[menu.main]]
  url = "product-category/honey-from-tnt-honey/"
  name = "Honey"
  parent = "product-category/food/"
  weight = 111.0

  [[menu.main]]
  identifier = "product-category/meat-and-poultry/"
  url = "product-category/meat-and-poultry/"
  name = "Meat and Poultry"
  parent = "product-category/food/"
  weight = 112.0

  [[menu.main]]
  identifier = "product-category/meat/"
  url = "product-category/meat/"
  name = "Meat"
  parent = "product-category/meat-and-poultry/"
  weight = 1000.0

  [[menu.main]]
  identifier = "product-category/meat/lamb/"
  url = "product-category/meat/lamb/"
  name = "Lamb"
  parent = "product-category/meat/"
  weight = 10000.0

  [[menu.main]]
  url = "product-category/meat/lamb/the-meatroom-free-range-lamb-soon-to-be-certified/"
  name = "The Meatroom"
  parent = "product-category/meat/lamb/"
  weight = 100000.0

  [[menu.main]]
  identifier = "product-category/meat/ryan-boon/"
  url = "product-category/meat/ryan-boon/"
  name = "Meat from Ryan Boon"
  parent = "product-category/meat/"
  weight = 10001.0

  [[menu.main]]
  url = "product-category/meat/ryan-boon/bacon-from-ryan-boon/"
  name = "Bacon"
  parent = "product-category/meat/ryan-boon/"
  weight = 100000.0

  [[menu.main]]
  url = "product-category/meat/ryan-boon/local-farm-sourced-beef-from-ryan-boon/"
  name = "Beef"
  parent = "product-category/meat/ryan-boon/"
  weight = 100001.0

  [[menu.main]]
  url = "product-category/meat/ryan-boon/game/"
  name = "Game"
  parent = "product-category/meat/ryan-boon/"
  weight = 100002.0

  [[menu.main]]
  url = "product-category/meat/ryan-boon/ostrich-from-ryan-boon/"
  name = "Ostrich"
  parent = "product-category/meat/ryan-boon/"
  weight = 100003.0

  [[menu.main]]
  url = "product-category/meat/ryan-boon/patties-boerewors-from-ryan-boon/"
  name = "Patties & Boerewors"
  parent = "product-category/meat/ryan-boon/"
  weight = 100004.0

  [[menu.main]]
  url = "product-category/meat/ryan-boon/free-range-oak-valley-pork-from-ryan-boon/"
  name = "Pork"
  parent = "product-category/meat/ryan-boon/"
  weight = 100005.0

  [[menu.main]]
  url = "product-category/meat/ryan-boon/gourmet-sausage-range-from-ryan-boon/"
  name = "Pork & Lamb Sausages"
  parent = "product-category/meat/ryan-boon/"
  weight = 100006.0

  [[menu.main]]
  identifier = "product-category/poultry/"
  url = "product-category/poultry/"
  name = "Poultry"
  parent = "product-category/meat-and-poultry/"
  weight = 1001.0

  [[menu.main]]
  url = "product-category/poultry/chicken-from-feed-me-free-range/"
  name = "Chicken"
  parent = "product-category/poultry/"
  weight = 10000.0

  [[menu.main]]
  url = "product-category/poultry/duck-from-feed-me-free-range/"
  name = "Duck"
  parent = "product-category/poultry/"
  weight = 10001.0

  [[menu.main]]
  url = "product-category/museli-granola/"
  name = "Muesli / Granola"
  parent = "product-category/food/"
  weight = 113.0

  [[menu.main]]
  url = "product-category/nut-butters-oh-mega-from-crede/"
  name = "Nut Butter"
  parent = "product-category/food/"
  weight = 114.0

  [[menu.main]]
  identifier = "product-category/seeds-dried-fruit/"
  url = "product-category/seeds-dried-fruit/"
  name = "Nuts, Seeds and Dried Fruit"
  parent = "product-category/food/"
  weight = 115.0

  [[menu.main]]
  url = "product-category/seeds-dried-fruit/flavoured-nuts/"
  name = "Flavoured Nuts"
  parent = "product-category/seeds-dried-fruit/"
  weight = 1000.0

  [[menu.main]]
  url = "product-category/seeds-dried-fruit/nuts/"
  name = "Nuts"
  parent = "product-category/seeds-dried-fruit/"
  weight = 1001.0

  [[menu.main]]
  url = "product-category/seeds-dried-fruit/seeds/"
  name = "Seeds"
  parent = "product-category/seeds-dried-fruit/"
  weight = 1002.0

  [[menu.main]]
  url = "product-category/seeds-dried-fruit/sulphur-free-dried-fruit/"
  name = "Sulphur Free Dried Fruit"
  parent = "product-category/seeds-dried-fruit/"
  weight = 1003.0

  [[menu.main]]
  url = "product-category/olives-preserved-lemons-jam/"
  name = "Olives, Garlic, Preserved Lemons, and Jam"
  parent = "product-category/food/"
  weight = 116.0

  [[menu.main]]
  identifier = "product-category/organic-fruit-vegetables/"
  url = "product-category/organic-fruit-vegetables/"
  name = "Organic Fruit and Vegetables"
  parent = "product-category/food/"
  weight = 117.0

  [[menu.main]]
  url = "product-category/organic-fruit-vegetables/fresh-fruit/"
  name = "Fresh Fruit"
  parent = "product-category/organic-fruit-vegetables/"
  weight = 1000.0

  [[menu.main]]
  url = "product-category/organic-fruit-vegetables/frozen-fruit/"
  name = "Frozen Fruit"
  parent = "product-category/organic-fruit-vegetables/"
  weight = 1001.0

  [[menu.main]]
  url = "product-category/organic-fruit-vegetables/fresh-herbs/"
  name = "Fresh Herbs"
  parent = "product-category/organic-fruit-vegetables/"
  weight = 1002.0

  [[menu.main]]
  url = "product-category/organic-fruit-vegetables/fresh-vegetables/"
  name = "Fresh Vegetables"
  parent = "product-category/organic-fruit-vegetables/"
  weight = 1003.0

  [[menu.main]]
  url = "product-category/sprouted-hummus/"
  name = "Sprouted Hummus"
  parent = "product-category/food/"
  weight = 118.0

  [[menu.main]]
  url = "product-category/stock/"
  name = "Stock"
  parent = "product-category/food/"
  weight = 119.0

  [[menu.main]]
  url = "product-category/sugar-alternatives/"
  name = "Sugar Alternatives"
  parent = "product-category/food/"
  weight = 120.0

  [[menu.main]]
  url = "product-category/household-cleaning-products/"
  name = "Household Cleaning Products"
  parent = "shop/"
  weight = 14.0

  [[menu.main]]
  url = "product-category/pesto-and-condiments/"
  name = "Pesto and Condiments"
  parent = "shop/"
  weight = 15.0

  [[menu.main]]
  url = "product-category/salts-and-seasoning/"
  name = "Spices and Seasoning"
  parent = "shop/"
  weight = 16.0

  [[menu.main]]
  url = "product/stainless-steel-straw-4-pack/"
  name = "Stainless Steel Straws"
  parent = "shop/"
  weight = 17.0

  [[menu.main]]
  identifier = "suppliers-2/"
  url = "suppliers-2/"
  name = "Suppliers"
  weight = 2.0

  [[menu.main]]
  url = "adres-kitchen/"
  name = "Adre's Kitchen"
  parent = "suppliers-2/"
  weight = 10.0

  [[menu.main]]
  url = "bytjiesalf/"
  name = "Bytjiesalf"
  parent = "suppliers-2/"
  weight = 11.0

  [[menu.main]]
  url = "by-nature/"
  name = "By Nature"
  parent = "suppliers-2/"
  weight = 12.0

  [[menu.main]]
  url = "crede/"
  name = "Crede"
  parent = "suppliers-2/"
  weight = 13.0

  [[menu.main]]
  url = "de-berge-2/"
  name = "De Berge"
  parent = "suppliers-2/"
  weight = 14.0

  [[menu.main]]
  url = "eric-swarts-organic-farmer/"
  name = "Eric Swarts – organic farmer"
  parent = "suppliers-2/"
  weight = 15.0

  [[menu.main]]
  url = "feed-me-free-range-2/"
  name = "Feed Me Free Range"
  parent = "suppliers-2/"
  weight = 16.0

  [[menu.main]]
  url = "foodology-2/"
  name = "Foodology"
  parent = "suppliers-2/"
  weight = 17.0

  [[menu.main]]
  url = "funky-ouma/"
  name = "Funky Ouma"
  parent = "suppliers-2/"
  weight = 18.0

  [[menu.main]]
  url = "gays-guernsey-dairy/"
  name = "Gay’s Guernsey Dairy"
  parent = "suppliers-2/"
  weight = 19.0

  [[menu.main]]
  url = "green-fish/"
  name = "Green Fish"
  parent = "suppliers-2/"
  weight = 20.0

  [[menu.main]]
  url = "heartveld-sprouted-goods/%20"
  name = "Heartveld Sprouted Goods"
  parent = "suppliers-2/"
  weight = 21.0

  [[menu.main]]
  url = "komati/"
  name = "Komati"
  parent = "suppliers-2/"
  weight = 22.0

  [[menu.main]]
  url = "metro-organics/"
  name = "Metro Organics"
  parent = "suppliers-2/"
  weight = 23.0

  [[menu.main]]
  url = "mooivallei/"
  name = "Mooivallei"
  parent = "suppliers-2/"
  weight = 24.0

  [[menu.main]]
  url = "neo-trading/"
  name = "Neo Trading"
  parent = "suppliers-2/"
  weight = 25.0

  [[menu.main]]
  url = "outcast-foods/"
  name = "Outcast Foods"
  parent = "suppliers-2/"
  weight = 26.0

  [[menu.main]]
  url = "ryan-boon/"
  name = "Ryan Boon"
  parent = "suppliers-2/"
  weight = 27.0

  [[menu.main]]
  url = "santa-annas/"
  name = "Santa Annas"
  parent = "suppliers-2/"
  weight = 28.0

  [[menu.main]]
  url = "the-berry-nice-company/"
  name = "The Berry Nice Company"
  parent = "suppliers-2/"
  weight = 29.0

  [[menu.main]]
  url = "thanks-goodness-foods/"
  name = "Thanks Goodness Foods"
  parent = "suppliers-2/"
  weight = 30.0

  [[menu.main]]
  url = "the-meatroom/"
  name = "The Meatroom"
  parent = "suppliers-2/"
  weight = 31.0

  [[menu.main]]
  url = "tnt-honey/"
  name = "TNT Honey"
  parent = "suppliers-2/"
  weight = 32.0

  [[menu.main]]
  url = "trump-and-timball-coffee-roasters-and-heartveld-sprouted-products/"
  name = "Trump and Timball Coffee"
  parent = "suppliers-2/"
  weight = 33.0

  [[menu.main]]
  url = "suppliers-2/two-dam-sustainable/"
  name = "Two Dam Sustainable"
  parent = "suppliers-2/"
  weight = 34.0

  [[menu.main]]
  url = "my-account/orders/"
  name = "Orders"
  weight = 3.0

  [[menu.main]]
  url = "favourites/"
  name = "Favourites"
  weight = 4.0

  [[menu.main]]
  url = "contact/"
  name = "Contact"
  weight = 5.0